### ISSUE TITLE
[I'm Feeling Lucky] Random Album album art does not load, and count is not correct for scrobbles

### ISSUE THREAD

**Issue by thereddestdog** [kawaiiDango/pano-scrobbler#422]
**Describe the bug**
Clicking random Track, Loved Track, or Artist will load art, but when clicking on Album, the art does not ever load. Also, the number of scrobbles displayed is not correct, I can't tell where the number is coming from. It seems like the scrobble count is only accurate for Tracks and Loved Tracks.

**App version**
v3.20

On mobile:
![image](https://github.com/kawaiiDango/pano-scrobbler/assets/24947579/957a030a-4c8d-46b4-bdf6-4e9e2f405848)

On Desktop:
![image](https://github.com/kawaiiDango/pano-scrobbler/assets/24947579/4a0e528c-63c9-4a25-baa0-0a510a9a67de)

**Comment by kawaiiDango** [comment]
The scrobble counts for random album and artist are from within the selected time period and are not the totals. Since this does not make sense in the app, and it would take another API call to get the total counts, I'm considering displaying the counts as "n scrobbles in [time period]” for those two tabs. The album art issue will be fixed in the next update.
