### ISSUE TITLE
[Feature request] Optional: Store location were you scrobble a song

### ISSUE THREAD

**Issue by Dtrieb** [kawaiiDango/pano-scrobbler#431]
I would like to have a optional option, to store my location were I scrobble a song.
Sometimes you remember the location but not the time, so it would be easier to to search for a place.

**Comment by kawaiiDango** [comment]
This will not be implemented due to how users and how Google look at apps with location permission with additional scrutiny. Also, resolving the geo-coordinates into text addresses requires sending your geo-coordinates to some online lookup service. Most users aren't expecting that from a scrobbling app.
