### ISSUE TITLE
Submission client and media player on scrobbles

### ISSUE THREAD

**Issue by regorxxx** [kawaiiDango/pano-scrobbler#433]
**Is your feature request related to a problem, or particular use cases? Please describe.**
Current jsonl implementation is missing some keys accepted at ListenBrainz payloads.

**Describe the solution you'd like**
Add these keys to the jsonl file:
- submission_client
- submission_client_version
- media_player

**Additional info**
Schema:
https://listenbrainz.readthedocs.io/en/latest/users/json.html#submission-json

I'm currently adding an import feature here:
https://github.com/regorxxx/ListenBrainz-SMP
Which will read the jsonl file and send listens to ListenBrainz on batch. 

It will check for MBIDs against the user library, if possible, and then use the data of the current scrobbles array. I can fill the submission_client and media_player obviously, but the version would require to be manually input everytime the user updates the app. Having all on your scrobbles data would be great.

**Comment by kawaiiDango** [comment]
I think submission_client and submission_client_version should be that of the importer app. Otherwise, all entries submission_client in the jsonl and CSV would have the same value. And putting the Pano Scrobbler version in there would not make much sense (different versions don't scrobble differently) except the fact that it is for submitting to listenbrainz. Pano Scrobbler does not send media_player to listenbrainz after #379 happened. I have removed the implementation, so it may take some work to add it back just for scrobbling to local files.

**Comment by regorxxx** [comment]
You are right, I have not thought about it (although I don't see a problem with all entries having the same value); technically the data is not being sent by your app in this case, true. Forget the request then.

About the second part, I'm not sure to understand the problem. Is related to sending the data online with media_player or just storing the name (even if it's not sent)?

**Comment by kawaiiDango** [comment]
Yeah it should be fine if stored offline. I implemented it anyways.
