### ISSUE TITLE
Weird UI offset

### ISSUE THREAD

**Issue by letruxux** [kawaiiDango/pano-scrobbler#474]
**Describe the bug**
UI is sometimes too much on the left sometimes too much on the right![Screenshot_20240701_125103.jpg](https://github.com/kawaiiDango/pano-scrobbler/assets/102257756/1bf429b9-1954-450b-8f45-d88c9a838d64)

**Steps to Reproduce**
open the charts tab

**App version**
3.35

**Additional info**

**Comment by Mehlsine** [comment]
I've got one as well since v3.29 but on scrobbles tab instead. Zero bug reports on this issue in 4 months, I guess I'm the lucky one here 😐
One UI 6.1, A14

First screenshot is from 3.27 version I'm currently on, the second one is 3.35 with that weird UI offset (the bug's been around since version 3.29 though as I mentioned above).

![Screenshot_20240801_222626_Pano Scrobbler](https://github.com/user-attachments/assets/2f4af357-f434-4674-9246-7f2fa3bbb455)
![Screenshot_20240801_221724_Pano Scrobbler](https://github.com/user-attachments/assets/1391513a-2289-40b4-b3b7-4b74085b8e6e)

**Comment by kawaiiDango** [comment]
The extra padding was added for TV overscan, which is required for submitting TV apps on play store.
https://developer.android.com/training/tv/playback/leanback/layouts#overscan

You may notice that there is more padding on the right. This is because the TV will actually use the tablet layout, with the navigation menu on the left, having its own extra left padding.

I didn't want to maintain yet another layout just for TV.

**Comment by Mehlsine** [comment]
Oh, okay. Thanks for the quick response.

There are also other little things that do not work as expected after that transition to TV-friendly UI in v3.29+, like opening scrobble info and other menus being somewhat clippy (as if it is putting a lot more effort into figuring out how to render on my screen than usual) and buttons not reflecting the system's Material You palette, they're just dark.

So overall that was a very questionable decision to be honest, considering that phone users are the main Pano Scrobbler's userbase and the UI elements here look somewhat off now in favor of much smaller TV's userbase 🫠

**Comment by zettaexa** [comment]
Please fix this ! Keeps bugging me off

**Comment by kawaiiDango** [comment]
The padding inconsistencies have now been fixed.

**Comment by letruxux** [comment]
i can confirm i don't see these inconsistencies anymore
