### ISSUE TITLE
Send playback duration instead of song duration

### ISSUE THREAD

**Issue by maya-doshi** [kawaiiDango/pano-scrobbler#476]
**Is your feature request related to a problem, or particular use cases? Please describe.**
Currently, for scrobble targets that support it (maloja in my case), the playback duration field is just the length of the track not the amount of time spent listening to the track.

**Describe the solution you'd like**
Send the playback duration instead

**Comment by kawaiiDango** [comment]
Thanks for pointing it out. The full track length will be sent in the "length" field instead of "duration" in the next update. But it is difficult to determine the amount of time spend listening to a track at the time of sending, as Pano sends scrobbles before one has finished listening to it, so, that will not be implemented.
